### ISSUE TITLE
Battery bar do not take all space when global scale set to 2

### ISSUE THREAD

**Issue by codelalala** [lonelytransistor/kde_batterybar#12]
First of all, this is a great widget!

I am using KDE with global scale set to 2. Therefore I am not sure the behavior when global scale is not 2. 

The Bug: The battery rate bar is double the length of the battery charge bar.

**Comment by lonelytransistor** [comment]
Are you sure you don't simply have only half an hour of battery charge left? In any case, you can use the rate bar rescaler in the config and set it to 0.5h or whatever value is correct for you.

**Comment by cipricus** [comment]
> The battery rate bar is double the length of the battery charge bar.

Where is the widget positioned?
Maybe somehow related: at some point, with the widget next to / left of the sys-tray , on a top plasma panel, the rate bar became extremely long to the left (even left of the widget position). I have fixed it by adding a "Margins separator" widget next to the batterybar widget.

![image](https://user-images.githubusercontent.com/3447868/207047719-e7f0a386-db1c-4e39-9a22-0f761d12330a.png)

**Comment by cipricus** [comment]
> double the length of the battery charge bar.

What's wrong with that?

 It seems to mean that in an hour your battery (charged at level X) would get 2X more energy if it could store it.

My battery charges so fast that the charging rate bar is almost always full (at least after a while). 

But it may be a good feature request to have instead or beside the present rate bar another charging bar that would show not the real level but the level one hour from now, whether charging or discharging.

**Comment by cipricus** [comment]
Or maybe it's the same problem as this: https://github.com/lonelytransistor/kde_batterybar/issues/15.

Anyway, I think the phrasing of the title here is wrong: "Battery charge bar do not take all space" because the problem is not with the charge bar, but with the rate bar, like you say in the body: " battery rate bar is double'

**Comment by codelalala** [comment]
> > double the length of the battery charge bar.
> 
> What's wrong with that?
> 
> It seems to mean that in an hour your battery (charged at level X) would get 2X more energy if it could store it.
> 
> My battery charges so fast that the charging rate bar is almost always full (at least after a while).
> 
> But it may be a good feature request to have instead or beside the present rate bar another charging bar that would show not the real level but the level one hour from now, whether charging or discharging.

Just make sure if I understand the feature correctly, it not only show the charge rate, but also for the discharge rate right? The battery charge bar is almost double the battery bar while I still have 5 hours battery life left.

**Comment by cipricus** [comment]
> it not only show the charge rate, but also for the discharge rate right?

Yeah, and it seems there is a problem here. Look at my recent issue https://github.com/lonelytransistor/kde_batterybar/issues/15

About the title: I think it should say the rate bar is too long, not the charge bar too short. It seems similar or identical to my issue. Were it not for your title, I would have posted under yours. It looks close enough.

**Comment by cipricus** [comment]
> the rate bar is too long, not the charge bar too short

The charge bar is the main one that shows what the battery charge is. If you put it to the left margin, it fills the entire panel to the right at 100%.  I find it too big (beside the fact that I prefer thin bars), so I put the widget more to the right, so it only fills the tray area at 100%. I have never found problems with that, I can always see the effective charge as a percentage of that 100% length. But the other bar is not working so good. I am using it like so: I have made both bars very thin (2 pixel) and set their position to always be the same while superposing each other (thus trying to avoid the bugs described in my issues).

When discharging, it looks like so:

![image](https://user-images.githubusercontent.com/3447868/207069543-9cace02d-e85f-4994-ad70-e79e0fc541c2.png)

The blue is the current 88% charge, the purple is what will be lost in one hour.

But when charging it looks sometimes like so:

![image](https://user-images.githubusercontent.com/3447868/207069915-3cb30024-996d-4591-bb2d-3896ec9b562d.png)

(here purple is the real charge, green is the amount/rate to be charged in one hour)

but just after a few seconds it looks like so:

![image](https://user-images.githubusercontent.com/3447868/207070072-9acfd0e5-2519-4bbd-bf2f-a671b7afcfb5.png)


I guess the last one is the expected one, where green is the rate charge completely covering real charge (because bars have the same position in settings), thus showing that my battery will be fully charged in less than an hour.

If instead of positioning the rate bar to the left, I put it to the right, it then goes while charging far to the left. If I don't superpose their positions and set them separate, then they seem to show the same case as what you describe. 

![image](https://user-images.githubusercontent.com/3447868/207072484-ae96b9b8-a6db-4fe0-8997-0f523ef1193b.png)


My present impression is that:

- this has nothing to do with scale
- you have the same bug as me, but you are describing it wrongly
- of course, I may be wrong :)

**Comment by codelalala** [comment]
> 

You are digging much deeper than I do. I do think I am describing it wrongly. I'll do some tweaking and see if I can make it work somehow

**Comment by codelalala** [comment]
> > the rate bar is too long, not the charge bar too short
> 
> The charge bar is the main one that shows what the battery charge is. If you put it to the left margin, it fills the entire panel to the right at 100%. I find it too big (beside the fact that I prefer thin bars), so I put the widget more to the right, so it only fills the tray area at 100%. I have never found problems with that, I can always see the effective charge as a percentage of that 100% length. But the other bar is not working so good. I am using it like so: I have made both bars very thin (2 pixel) and set their position to always be the same while superposing each other (thus trying to avoid the bugs described in my issues).
> 
> When discharging, it looks like so:
> 
> ![image](https://user-images.githubusercontent.com/3447868/207069543-9cace02d-e85f-4994-ad70-e79e0fc541c2.png)
> 
> The blue is the current 88% charge, the purple is what will be lost in one hour.
> 
> But when charging it looks sometimes like so:
> 
> ![image](https://user-images.githubusercontent.com/3447868/207069915-3cb30024-996d-4591-bb2d-3896ec9b562d.png)
> 
> (here purple is the real charge, green is the amount/rate to be charged in one hour)
> 
> but just after a few seconds it looks like so:
> 
> ![image](https://user-images.githubusercontent.com/3447868/207070072-9acfd0e5-2519-4bbd-bf2f-a671b7afcfb5.png)
> 
> I guess the last one is the expected one, where green is the rate charge completely covering real charge (because bars have the same position in settings), thus showing that my battery will be fully charged in less than an hour.
> 
> If instead of positioning the rate bar to the left, I put it to the right, it then goes while charging far to the left. If I don't superpose their positions and set them separate, then they seem to show the same case as what you describe.
> 
> ![image](https://user-images.githubusercontent.com/3447868/207072484-ae96b9b8-a6db-4fe0-8997-0f523ef1193b.png)
> 
> My present impression is that:
> 
> * this has nothing to do with scale
> * you have the same bug as me, but you are describing it wrongly
> * of course, I may be wrong :)

You are digging much deeper than I do. I do think I am describing it wrongly. I'll do some tweaking and see if I can make it work somehow

**Comment by cipricus** [comment]
> I'll do some tweaking

First, test if we have the same problem by moving the widget to the right, close to the tray but left of the tray (not right of the tray):

![image](https://user-images.githubusercontent.com/3447868/207062040-981d5e9b-a2f7-4771-aae7-be58c68a565b.png)

In edit mode, right-click the battery-bar widget, go to its settings and select the position of the _rate bar while charging_ to _right_ ("bottom" or "top" no matter but _opposite_ to the other bar).

After a while, it should go too far to the left while charging, as seen in my last image of previous comment .

**Comment by codelalala** [comment]
> > I'll do some tweaking
> 
> First, test if we have the same problem by moving the widget to the right, close to the tray but left of the tray (not right of the tray):
> 
> ![image](https://user-images.githubusercontent.com/3447868/207062040-981d5e9b-a2f7-4771-aae7-be58c68a565b.png)
> 
> In edit mode, right-click the battery-bar widget, go to its settings and select the position of the _rate bar while charging_ to _right_ ("bottom" or "top" no matter but _opposite_ to the other bar).
> 
> After a while, it should go too far to the left while charging, as seen in my last image of previous comment .

You are using kde panel or the latte-dock panel?

**Comment by cipricus** [comment]
> kde panel or the latte-dock

default plasma panel

**Comment by lonelytransistor** [comment]
This was caused when using PM source I think. Sometimes it returned a negative value. It seems that if you just take an abs of it you get the correct value.
